### ISSUE TITLE
Search with space at end crashes app

### ISSUE THREAD

**Issue by PanderMusubi** [segler-alex/RadioDroid#12]
Search with space at end crashes app. Please trim/strip any search. Also make search more robust for handling spaces.

**Comment by segler-alex** [comment]
i do encoding for searches now, should not happen again

**Comment by Vrihub** [comment]
I don't know if it's related to this bug(fix), anyway: currently a space at the end of the search string is considered part of the search pattern, while it should be trimmed/ignored instead.

e.g. if you search for "jazz " (final space), you'll get stations that contain "jazz" in the middle of their name, but you won't get those that have "jazz" at the end of the name (because the final space is missing).

This is quite relevant because predictive text systems like the one on my android device automatically add an extra space at the end of the word when you choose it from the suggested words list.
