### ISSUE TITLE
No chromecast on F-Droid version?

### ISSUE THREAD

**Issue by kulmegil** [segler-alex/RadioDroid#155]
The v0.37 from f-Droid does not display cast icon.
v0.36 and beta v0.37 from Play Store does - works as expected for me.
Are those editions different?

**Comment by SpotComms** [comment]
Chromecast support is not available in the F-Droid variant, as it would require utilizing Google's proprietary Play Services library, which would disqualify it from the F-Droid inclusion policy.

**Comment by kulmegil** [comment]
Differences between variants are disturbing.
Probably I wouldn't even be aware of Chromecast support if I skipped a quick look at changelog.

There is also MicroG framework, but does not support Cast API yet (microg/android_packages_apps_GmsCore#79)

F-Droid can tag apps with so called "[antiFeatures](https://f-droid.org/wiki/page/Antifeatures)" and I was wondering if RadioDroid can pass when part of the optional functionality depends on G.S.F. Like making app detect if G.S.F. is present on device and enable chromecast support only then?

Otherwise it would be good to include the clear message in F-Droid description that part of it's functionality is not present when F-Droid variant is used. I generally prefer downloading from F-Droid by default since some Play variants are more aggressive versions with ads/data collection added.

**Comment by SpotComms** [comment]
Even if microG had cast support and was installed and it was marked as an anti-feature it wouldn't matter. F-Droid does *not* allow the inclusion of proprietary code in the apps it distributes. I am not talking about Google Play Services, we are talking about the actually library the app interacts with: com.google.android.gms:play-services-cast and com.google.android.gms:play-services-cast-framework both of them are proprietary.

You can find many examples of this by looking at Conversations (no GCM), Muzei (no Wear), DSub (no Cast), SkyTube, (no YouTube), etc. they all have variants that have slightly less features due to not having proprietary code included.

**Comment by Korpip** [comment]
F-Droid version has Chromecast support in the description.

**Comment by segler-alex** [comment]
i made a pull request to f-droid repo for removing chromecast support in features list
https://gitlab.com/fdroid/fdroiddata/merge_requests/5160
