### ISSUE TITLE
Not playing certain radio stations

### ISSUE THREAD

**Issue by tanty** [segler-alex/RadioDroid#165]
I'm experiencing some playback problems recently.

Libre FM:
http://www.radio-browser.info/gui/#/edit/89979

Used to work and still does from the web browser.

This is the direct link to the radio station playlist:
http://37.14.48.219:8000/listen.pls?sid=2

Now, RadioDroid doesn't spit any error and behaves as if it would be playing the radio, but nothing is really played. What I can see from the notifications applet is that the radio timer starts counting from 00:00 to 00:03 and, then, jumps again to 00:00.

**Comment by FrankEular** [comment]
I also suffer from the same issue, version 0.37.

Sometimes it acts differently: it does play, but after some seconds the timer jumps to 00:00.

**Comment by werman** [comment]
It seems I found the issue (reproduced on android 4.4.4): 
Non standard http response 'ICY 200 OK' which isn't handled properly on some old versions 
[https://stackoverflow.com/questions/21812483/unexpected-status-line-icy-200-ok-for-url-openstream-method](stackoverflow). (However I experienced the same issue on the latest android versions)

Instead of the android built-in http client implementation custom one should be used.

I will add okhttp as a new dependency and see if this solves the issue.

**Comment by werman** [comment]
I fixed the issue, I'll create a pull request tomorrow. Also'Libre FM' which was linked by @tanty continuously produces error 'E/AudioTrack: Discontinuity detected' which leads to constant stuttering but this is another issue which should be investigated.

@FrankEular Could you specify the station with which the issue occurred to make sure I fixed the error in question and not some other?

**Comment by FrankEular** [comment]
Yesterday I met many stations with which the issue occured but for the moment, I found the same thing for BBC Radio 4, but I need to confirm whether it's an issue of network connection or RadioDroid.
