### ISSUE TITLE
Add Some Features : manual Url input by user, Backup, restore, contributing to add channel 

### ISSUE THREAD

**Issue by AhmedNazir** [segler-alex/RadioDroid#171]
A great app.
But I feel it needs some features to be more productive.

Add an option for inputing Stream URL. an backup and restore option also needed to save these link.
I am Bengali. I want to add Some radio Stream URL. but I don't find any option.
thanks for creating such a great app

**Comment by Wikinaut** [comment]
Add a tool to import/export favorite station list per OPML https://en.wikipedia.org/wiki/OPML file, similar to what Stefan's https://play.google.com/store/apps/details?id=de.shandschuh.sparserss&hl=de does (export a list of one's seletion of RSS feeds in OPML format)

**Comment by Wikinaut** [comment]
see 

#33 
#132

**Comment by Cormak** [comment]
@AhmedNazir you have to go to http://www.radio-browser.info and add the station to their Wiki. It's not as handy as being able to add your own station from the app itself, but currently they have no way to add stations to the wiki from the app itself.

**Comment by Wikinaut** [comment]
@AhmedNazir Just as side information:

The Transistor App (source https://github.com/y20k/transistor ) https://play.google.com/store/apps/details?id=org.y20k.transistor is a simplistic app which only works with user-supplied stream urls.

> Transistor is a bare bones app for listening to radio programs over the internet. The app stores stations as files on your device's external storage.

**Comment by maszek** [comment]
> Add an option for inputing Stream URL. 

I think what you meant to say by asking for "inputting stream URL" is that you would use it for _tuning_. Some stream sources that you can find on http://www.radio-browser.info/ or elsewhere online are hard to identify, since proper tags are missing. This makes it harder to tune into them on RadioDroid. In some cases, all you can go by are IP-addresses.

As a workaround, I did find out that if you enter the stream-URL in the address bar of your browser, followed by **/?** it will take you to SHOUTcast Stream Status, which will supply more information about the stream's source. It will even work with IP-addresses (syntax: http://###.###.###.###:####/?). This may enable you to find the stream in RadioDroid.

Other than than that: great app. I just migrated from Transistor, but that one requires too much manual labour ;-)
