### ISSUE TITLE
[Bug] All BBC streams make trouble. Cannot be played because of interruptions every n seconds.

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#229]
Can someone confirm, that BBC streams make trouble (playing starts and stops every n seconds)?

Examples: BBC World Service; BBC 4

* HUAWEI P8 LITE 2017
* Android 7.0
* RadioDroid Play Version (and also master branch github versions)

**Comment by werman** [comment]
Can confirm, same for me.

**Comment by Wikinaut** [comment]
@segler-alex can you check on your device/s ?

**Comment by Wikinaut** [comment]
I checked BBC 4 on debian 
```http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p```
Works there without apparent problems.

**Comment by Cormak** [comment]
@Wikinaut I can confirm the same behavior on Radiodroid 0.46 on a Moto X Pure with 7.1.2 

Some interesting observations: 

When using the direct link which is http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-einws

- It plays without interruption on Foobar2000

- It plays without interruption on MPC-HC

- It plays without interruption on mpv

- The Tunein page also seems to use the same direct link https://tunein.com/radio/BBC-World-Service-News-s24948/

Whatever playback backend Radiodroid uses, it doesn't work with this link without stopping every few seconds and restarting. What backend does Radiodroid use anyway? Perhaps it simply needs to be updated?

**Comment by werman** [comment]
I doubt the issue is in the backend, probably there is something unexpected in the station's stream where our code fails. It should be debugged.

**Comment by Cormak** [comment]
@werman Correct me if I'm wrong, but it seems we have more than one player backend within Radiodroid. 

https://github.com/segler-alex/RadioDroid/tree/master/app/src/main/java/net/programmierecke/radiodroid2/players

If that's the case, why not just rely on Exoplayer for everything as it is the most modern, up-to-date, open-source backend? Every open source project seems to be doing just that. 

I noticed the notification saying "stop old player" when looking closely into this issue. 

https://github.com/segler-alex/RadioDroid/issues/251

Why even have more than one player or an "old player"? We should just make Exoplayer the only player as it seems to have the most success in playing AAC+ and Opus streams anyway while the "old player" has to be stopped and switched to Exoplayer, which plays absolutely everything without issue.

**Comment by werman** [comment]
@Cormak Yes, there are two player backends: one MediaPlayer for API< 16 and ExoPlayer for later APIs. So any new android uses ExoPlayer.

**Comment by Cormak** [comment]
@werman but why does it say "old player"? I mean, logically, one would think that means that the old player was stopped in order for the new player to take over. 

What about when it says "starting proxy"? What proxy? It's very confusing to see such messages in the notification. 

Furthermore, considering that only 1% of Android users are still on API<16, maybe its time to remove that old mediaplayer and just go with Exoplayer. 

@Wikinaut I think we're on an older version of Exoplayer as well because the BBC World Service Stream plays perfectly with https://github.com/y20k/transistor and that is currently using Exoplayer 2.5.1 at the moment. 

Therefore, I think updating to the latest Exoplayer will solve this bug.

**Comment by werman** [comment]
@Cormak The status messages at the moment aren't user friendly because no one bothered to change them, they mean nothing to the end user, they just expose internal logic.

We already have support of old MediaPlayer, it is already working and shouldn't require any maintenance so I would rather left it intact for now.

As for ExoPlayer, I agree, it should be updated.

**Comment by Wikinaut** [comment]
exoplayer updated to 2.5.4, but this does not solve the issue!

**Comment by Wikinaut** [comment]
I compiled this tiny radio-player for all BBC streams https://github.com/Wikinaut/radio-player . This one works.

**Comment by Wikinaut** [comment]
May be a problem with "Proxy" ?

**Comment by Wikinaut** [comment]
@segler-alex könntest Du Dir das Problem mit (allen) BBC Sendern mal anschauen, evtl. debuggen?

**Comment by segler-alex** [comment]
i could reproduce the problem on my phone, there was a sockettimeout in okhttp
when i increased the readtimeout from 2 to 10 seconds it went away.

**Comment by segler-alex** [comment]
i pushed a new version to google play beta channel

**Comment by werman** [comment]
@segler-alex Came to the same conclusion - increasing read timeout helps. For some reason these stations don't behave nicely.

**Comment by Wikinaut** [comment]
great! I confirm that your fix https://github.com/segler-alex/RadioDroid/commit/022290470225c7f16891dc2d6212d796d85f2673 solves this issue.

**Comment by Cormak** [comment]
Wow, a 2 second timeout? I rarely see that in media players. No wonder it wasn't playing correctly. Timeouts tend to be 5 seconds or more. Nice job with the fix. It's working as expected.
