### ISSUE TITLE
Cannot listen to AAC+ stations

### ISSUE THREAD

**Issue by Zeralda** [segler-alex/RadioDroid#251]
I can listen to MP3 stations but not to AAC+. I get this message: "The player doesn't support this type of audio file". Is this an issue with Radiodroid or does the app work together with a sound player that I would have to install? Thank you! (I use a Fairphone 2, Android, no GSF)

**Comment by Wikinaut** [comment]
@Zeralda please add (here) some example stations.

**Comment by Zeralda** [comment]
I have been trying to listen to radiovostok.ch
I tried two AAC+ stations from the "topclick" list, which didn't work either.

**Comment by Wikinaut** [comment]
@Zeralda Please let me know what exactly I have to enter into the station search to find that station in RadioDroid App.

**Comment by Zeralda** [comment]
vostok works for me. The full name is Radio Vostok.

**Comment by Wikinaut** [comment]
On my Android 7.0, it plays this station!

**Comment by Zeralda** [comment]
OK... My Android is 6.0.1, open source build for Fairphone (i.e. no Google Services Framework installed).

**Comment by Wikinaut** [comment]
I am sure, it's again a Fairphone-specific bug, that it cannot play AAC+ because most likely the Fairphone player does not support it. Perhaps you can use a different external player like VLC ? I am not sure about this, because I never tried taht,

**Comment by Wikinaut** [comment]
RadioDroid as such supports external players; use the latest version from github and report here, please.

**Comment by Zeralda** [comment]
OK, I'll try. Do you know about any Open Source alternatives to VLC?

**Comment by Zeralda** [comment]
Btw the Fairphone player ist the Android stock "Music" app.

**Comment by Zeralda** [comment]
Just checked and apparently, you’re right - thought it wasn’t because it isn’t available on F-Droid (https://forum.f-droid.org/t/where-is-the-vlc-app/108/4 <https://forum.f-droid.org/t/where-is-the-vlc-app/108/4>).

**Comment by Cormak** [comment]
@Zeralda @Wikinaut I tried that station just now and it plays back fine on my phone but I get weird messages on the notification before and during playback such as "stop old player..." and "starting proxy"

This is on a Moto X Pure Edition with 7.1.2 with Radiodroid 0.46 beta from Google Play.

Also, I'm not sure why a Fairphone wouldn't be able to play this station with Radiodroid because AAC+ has been supported natively on Android since 4.1

https://developer.android.com/guide/topics/media/media-formats.html

However, the issues with that station might improve if he changes the URL to the one found on the homepage of the station he is telling us about. 

https://www.radiovostok.ch/ecoute.htm

http://statslive.infomaniak.ch/playlist/radiovostok/radiovostok.aac/playlist.pls

Personally, I find that using the links given to us on the station homepages are best because the raw links such as the one currently on the radio browser wiki can change from time to time while the .pls URL always just forwards to the current raw URL.

**Comment by Zeralda** [comment]
I installed VLC and it seems to work now! Thank you! 
(Using RadioDroid from F-Droid and VLC from Yalp store)
