### ISSUE TITLE
[Regression in 0.50] Musik title is no longer part of the filename

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#273]
The 0.50 has a regression: the musik title is no longer printed as part of the filename.

Please restore this feature.

**Comment by werman** [comment]
I indeed removed it and didn't mention or ask about it, sorry. I can propose to make an option with filename formatting and/or selection from predefined formattings. Also isn't recording used to record more than one song? Since I don't use this feature I'll ask in what cases do you use it? Maybe I can think of some improvements when I'll understand usage of the recordings.

I have different use cases in my mind at the moment:
1. Record non music stations since they may have original content which isn't easily found later. 
2. Record music station for a while (many songs) to play it later offline.
3. Record current playing song for whatever reason.

So I can think of next features for recording, I'll list them out of any order:
- Record current playing song from its start. We can store certain amount of data in buffer until new song starts. If recording is started we can write it from song start. Will be good for case 3.
- Automatically record station at certain time in the future for defined time. Could be useful for 1.
- Encode stream into another format (with lower bitrate). Could be useful for 2. and 1.
- Add metadata to recorded file with song titles, it will make possible to see which song is currently playing in recorded file.  
- Record station in background, record several station at time. Useful for 1. and 2. See #262

**Comment by Wikinaut** [comment]
I use(d) this feature (artist and song title in the recorded filename) for memorizing songs which were played. For example wit SomaFm Groove Salad station.

So I ask you to please restore this.

If you want, as an option, but please enable that by default (if you can live with that default), so that the previous filename scheme is kept for all my devices.

Regarding your ideas:
I only would recommend a new feature "start a new record file when (artist/title) id 3 tag changes", which in consequences would automagically write one file per song.

**Comment by werman** [comment]
Understood, I'll restore the formatting
