### ISSUE TITLE
[Suggestion] Have navigation drawer alongside with bottom navigation.

### ISSUE THREAD

**Issue by werman** [segler-alex/RadioDroid#281]
After introduction of bottom navigation you either have bottom navigation with 5 items which doesn't cover all screens or have navigation drawer. 

Material guidelines [state](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage):

> If your top-level navigation has more than six destinations, provide access to destinations not covered in bottom navigation through alternative locations, such as a navigation drawer.

So it seems ok to use navigation drawer with bottom navigation when there is a need to access many destination with some of them being preferred (the ones in bottom navigation). We need recordings screen, maybe about screen, in future player screen and some others (like playlist or whatever) accessible.

**Comment by avently** [comment]
There is a button, which opens recording screen from mini player.  Maybe its not what you saw before in the app but it looks logical. When you will make player larger you can show recordings in that new interface. 

>If your top-level navigation has more than six destinations

For now 5 destinations is ok. We can use navigation drawer with bottomnavview now too but it looks and feels so bad. I prefer to make a good UI. That's why I replaced drawer. 

>maybe about screen

How often you open about screen? First time when download the app and second time when you have been making translation? :) That's not the case when we really need to make two navigation elements in one screen. Or I can add it to the drawer if you wish (only if you will not use bottomnavview of course).

**Comment by werman** [comment]
Ok, maybe it would be possible to have all necessary navigation from future player screen. I'll close the issue for now.
