### ISSUE TITLE
Broken equalizer presets

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/RadioDroid#310]
Steps to reproduce
* Open the Settings -> Equalizer in AndroDroid
* Turn On the Equalizer
* Change FX booster to any other preset -- it won't work

**Comment by werman** [comment]
What android version and what equalizer? Does this equalizer work for other applications? It works for me on latest LineageOS with AudioFX built-in equalizer, also it worked on other android versions with another equalizer. Probably I should try other custom equalizers to be sure.

**Comment by davidhedlund** [comment]
@werman The Equalizer in Androdroid in Settings.

**Comment by werman** [comment]
@davidhedlund We rely on 3rd party equalizers so "Equalizer" setting just ask android to launch whatever equalizer it has. So most probably it's something wrong with equalizer itself. You could try to find out whether equalizer work for other apps, if yes - then more investigation will be necessary.

**Comment by davidhedlund** [comment]
@werman 
> You could try to find out whether equalizer work for other apps, if yes - then more investigation will be necessary.

Good detective work. Can you please suggest how I can evaluate it? I don't find any GUI in Android itself.

**Comment by werman** [comment]
@davidhedlund You can install a player which supports equalizer e.g. [Jockey](https://play.google.com/store/apps/details?id=com.marverenic.music&rdid=com.marverenic.music) and try equalizer there. The equalizers especialy built-in ones aren't very transparent in what they do and they are different between vendors. Also you can try to install some custom equalizer. Since the equalizer functionality on RadioDroid's side is very simple there isn't much I can suggest or troubleshoot without physical access to device in question.

**Comment by davidhedlund** [comment]
@werman Thanks. The Equalizer didn't work in Jockey either.
