### ISSUE TITLE
[feature request] Add full window for radio infos and stuff

### ISSUE THREAD

**Issue by Rubylion** [segler-alex/RadioDroid#352]
Hi. Would it be possible to have a player tab opened when the actual station is playing and is clicked on at the bottom player? On this tab there could be a bigger view of the cover and infos provided from the station. Also there could be space for streaming info (as asked for in issue #349) and why not putting the record button there too? Would make things more sorted and readable, like artist info etc.

**Comment by werman** [comment]
Hi, yes it's a feature I wanted to make for some time since #263, such screen will make possible to add a lot of useful functionality. The only issue is the time.

I'll list everything I think such screen should contain:
- Everything available in station card (which is in station list)
- Everything available in the current mini player
- Current album art if available
- More detailed playback info
- Display lyrics of the current song - via external app
- Playback history - songs with timestamps with ability to quickly search them in browser/lyric app, maybe some other info.

**Comment by Rubylion** [comment]
Sounds great. Hope you will find some time sometime. Thx

**Comment by neelayak** [comment]
If possible i would love to design the front for the app sir @werman

**Comment by werman** [comment]
@neelayak Could you clarify your intent? Do you want to make mockup of this screen? If yes - it would be great.

**Comment by neelayak** [comment]
Ya sir I mean I want to make a mockup of this screen, As I am using this
library in my app this is the least I can contribute to the community. If
you tell me what are data you want to show it will be helpful for me also

**Comment by werman** [comment]
I would like you to research how player window looks like in other radio apps. I have listed desired info in second comment, I'll try to make it more detailed so how I envision the screen:

- Two major parts are player itself at the top and history of the playback at the bottom, since history may be big this whole screen is scrollable (not really sure about this - maybe history should have separate screen with only one or two items on player screen)

In background of the screen probably should be current album art.

Player part:
- There should be station name, station website which is visible and clickable. Also somewhere nearby station bit rate, codec, language, country
- Station icon ? 
- Station tags should be shown somewhere, I'm not sure if they should have same design as tags on station's card
- Share/Favourite/Alarm button
- Playback/Record controls and information:
  - Play/Pause buttons
  - Prev/Next station buttons
  - Record button and some space for information about recording:
    - Filename we recording into, probably clickable.
    - Size and length of the recording

History part is a list of history items:

- Song with a timestamp
- Station name and icon with song and timestamp will be created when station is changed/played
- Network error while playback or other errors. No need to design for now since I'm not sure about this one

User should be able to copy song's name and see song's lyrics (lyrics viewing is delegated to the other app so it should probably be some kind of button or context menu)
User should be able to copy station name and go station's website from history.

Feel free to change/suggest anything and ask questions. I'll answer them when will be available.

**Comment by werman** [comment]
@neelayak Sorry for the late answer, I believe there is some misunderstanding here. Let's resolve it. 
1) Do you want fully implement this screen? Code + UI?
2) The lyrics will be handled by external app e.g. QuickLyrics (it's already works with our notification), we only need to correctly pass necessary data - song name. 
3) "As of now I am trying to integrate the library will my music player app" - could you clarify what do you mean with this?

**Comment by neelayak** [comment]
Ya sir I want to implement your radio app with the front player and I can
implement the front with the code but few changes I have done
1. Listviewcompact was showing error so I changed to listview.
2 . Lyrics I thought to get it via some API as I am doing it in my app.
3. I am trying to publish a music player for last 2 year but the app is not
getting that much download so this is my 4 trying to publish a better app .
That's why I was searching for radio streaming API but by referencing your
project I can easily integrated it with the radio app now .
4 . My app is in beta now
https://play.google.com/store/apps/details?id=com.musicplayer.music.audioplayer

**Comment by werman** [comment]
Ok, this clears some things. But I still don't understand the connection between RadioDroid and your application.

**Comment by neelayak** [comment]
Sir I am making an app which can be a music player as well as a radio
streaming app. That's how your library comes into play as I can use your
code as a reference .

**Comment by werman** [comment]
Ok, cool. So you also want to improve RadioDroid by implementing player window. If you start doing it, please, show your progress here periodically since the feature is big, I'll try to give advices if something will go wrong.

**Comment by neelayak** [comment]
Ok , Sir I will be doing some searching till 8 july as my colleague is over
from 5 july and traveling makes it difficult to work in development
 So far my plan is to make a singleton class and using handler I will be
updating the data  and sending receiving the data in the activity as I am
doing in my app too . If you know a better way plz let me know .

**Comment by neelayak** [comment]
Can I get an email address so I can message you on hangout discussion in
GitHub thread is quite weared I guess as it is going to be a long one .

**Comment by werman** [comment]
You can write to wermaan@gmail.com

**Comment by Cormak** [comment]
This is much needed because right now the UI is confusing compared to other radio apps. New users may get turned off and we want them to use Radiodroid rather than those crappy, ad-infested radio apps.

**Comment by neelayak** [comment]
Sir In the front I am using white icon so for both the theme it will be
same, I never worked with the theme if you give some hint it will be
helpful , Will I have to set the color and imagebutton separately or the
text color will be handled automatically??

**Comment by AdityaMH** [comment]
Is fullscreen player work canceled? I don't see fullscreen player anywhere.

**Comment by segler-alex** [comment]
this will be in the next release
