### ISSUE TITLE
Make Long Names Scrolling in Mini Player

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#429]
If the station name or the live info is too long, it will be cut to show only a part of it. It’s better to show scrolling texts in the mini player.

**Comment by werman** [comment]
Yep, it was mentioned several times somewhere. And I'm making this change as a part of work on new player screen.

**Comment by zo-shin** [comment]
Thanks, I'm expecting that.

**Comment by avently** [comment]
@werman hey. Came here just to ask you about new player UI which was mentioned a year ago:)
Any release date exists?

**Comment by werman** [comment]
Uh, This time I'm actually doing something, you can see it in this branch: https://github.com/werman/RadioDroid/commits/feature/player-screen

There is full a screen player which opens with swipe from small player, it can fetch album art (which crashes at the moment) there is a played tracks history. And there is a rework of MPD because why not... (not tested) Half of the reason it's moving so slow is that it impossible to just add this one screen - I'm always finding issues along the way.

**Comment by avently** [comment]
@werman what do you plan to do with MPD? I'm using it and seems like no bugs exist at the moment

**Comment by avently** [comment]
Didn't look at your code but maybe it will be useful. There is a good library for sliding a view from the bottom to top (or in another direction) 
https://github.com/umano/AndroidSlidingUpPanel
I use it in one of my projects. Works well. Use-case are identical to what you want to do

**Comment by werman** [comment]
@avently The rework is not due to bugs but because it's a pain to work with thus I tried to move it under PlayerWrapper interface.

Ok, if we have at least one user of MPD at the moment we can test my assumptions before I do more work on it:
- MPD is just another type of player, you don't want to hear stations via MPD and phone simultaneously.
- It's good to be clear what MPD server is used and when it is used, consider the flow I have in mind, you click "Connect to MPD" -> selection from saved servers -> server selected and connected -> you can play station. 

> https://github.com/umano/AndroidSlidingUpPanel

Looks nice, however I already implemented what I believe works using BottomSheet and unless my implementation has some critical flaws I would be reserved to pull one more external lib (I already pulled enough of them) and from that repo it doesn't look like it is being actively supported.

**Comment by werman** [comment]
I see, makes sense, interesting. Then my flow is not valid.

So you want to control what is played on your phone and what is played via MPD and this playback may happen simultaneously? What if from the point when we are connected to MPD we always have a choice to play station locally or play station via MPD? And same for pausing.

**Comment by werman** [comment]
Overall if you can describe the best workflow you can think - I will appreciate it. Or I can revert to current way of handling MPD and address it later.

**Comment by avently** [comment]
>What if from the point when we are connected to MPD we always have a choice to play station locally or play station via MPD? And same for pausing

No sure how UI should look like for this feature. But if can create that UI with usability in mind - why not, useful feature.

My workflow is simple. I have multiple MPD servers in my house. Some of the servers located inside "public" rooms, like guest room, kitchen. Music can be played on any of them. So someone can ask me to turn on music and I'll do it. Then I'll go to write a code for projects and music keeps playing without my attention. 

One more use-case in mind. Maybe it would be a good idea to make something like music transport from currently playing music on Android to MPD server. By steps:
- play any sound in any app on Android
- make this sound playing via remote MPD server without playing on phone (while this option selected in UI, of course)

That way you can play not only radio but any audio (saved recordings included) from any app via MPD server that was setup in RadioDroid. Similiar famous way used with playing music via Bluetooth but here we can use MPD server like modern geeks:)

**Comment by avently** [comment]
>to capture all music on phone, create server and make MPD connect to it and thus stream music from phone

create server?  Server already created somewhere in the house. We need to capture all music on phone, connect to MPD server, stream the music. Since this somehow works with Bluetooth maybe it can work without Blootooth. But I'm not sure it's possible with actual Android API.

**Comment by werman** [comment]
I mean, you cannot stream music via MPD as far as I understand, you can ask MPD server to do something like play from url so in order to stream music from phone using MPD you'll need to create http server on phone and ask MPD server to stream from this server.

> But I'm not sure it's possible with actual Android API.

I'm not sure either.

**Comment by avently** [comment]
>create http server

Yep, streaming works from active http server, your are right. It shouldn't be a big problem but how to capture all the music... that's a question
