### ISSUE TITLE
 When restarting RadioDroid play the last played station (user preference)

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#55]
Pls. add this as a user option.

**Comment by zoff99** [comment]
maybe please rather make a "widget" to put on your homescreen. when you touch the widget it will play the first entry in your favorites list

**Comment by Wikinaut** [comment]
Alex, can you please implement this ? Item is still the top of my wish-list. 

I would really like to have RadioDroid starting with the last played station.

**Comment by segler-alex** [comment]
how would you like the feature to behave? at the moment there is no real time were radiodroid stops and therefore the currently played station stops. 
even if you close radio droid the play will continue, because a background service is started. you have to press stop in the background service to stop playing. 
in which case should a stream start again?just start playing the last played stream (which was stopped by hand in the background service with the stop button) every time the user clicks on the radio droid symbol on her/his homescreen?
could you give me a hint how you would like it to behave? how you would like to use it?

**Comment by segler-alex** [comment]
i like the idea of a widget, maybe display favourites in widget?

**Comment by Wikinaut** [comment]
@segler-alex 
When RadioDroid starts, it should start playing with the station on top of the "History" list ("Verlauf").

**Comment by Wikinaut** [comment]
I don't like widgets, they took too much icon screen space, and a widget is really not needed for this small functional improvement. Just start playing with the last selected station, i.e. the station currently on top of the last-played "History".

**Comment by zoff99** [comment]
better make a widget that when pressed just plays that station.
its not so good to start playing every time you open the app. just image when you are in a quiet place and just want to browse stations. then it would also start to play.

**Comment by segler-alex** [comment]
maybe it would be a good idea to do it like the radio player "Transistor".
It allows radio stations to be placed as extra links/apps on the desktop. if you press on them, they will start immediately without opening the radiodroid app.
you can easily create a link like that from radiodroid by clicking on "..." of a station and clicking "add to desktop"
how would you feel about that?

**Comment by Wikinaut** [comment]
+1

Okay, I had this idea, too, but was reluctant to also propose this.

**Comment by zoff99** [comment]
+1

**Comment by Wikinaut** [comment]
The introduction of the preference setting "start RadioDroid with history view" https://github.com/segler-alex/RadioDroid/commit/b72ec9472e5bb864f30b5aad8adcd0e339038201 is a solution, which is only **one** click away. I am closing this issue therefor.
