### ISSUE TITLE
Change user option default for "Auto-favorites"

### ISSUE THREAD

**Issue by aha999** [segler-alex/RadioDroid#664]
Pressing on any radio automatically puts it to favorites, which is imo annoyance, because it messes up the favorites and adds new things just because you pressed the radio to listen to it or to see what music is it playing, it's not wanted that it's automatically put to favorites just because you open it.

Add to favorites option is already present in the submenu of the radio on the right side of radio stations.

Please remove the antifeature which puts any radio station in the favorites just because you press on it to listen to it.

EDIT: found the setting that reverts that. By default, the progam shouldn't put everything you play to favourites imo, because there's already History menu for recently played stations. 

edit 2: changed the title

**Comment by Wikinaut** [comment]
He, no! There is already an user option in Interaction > Auto Favorites where you can easily permanently disable this function (which I need).

**Comment by aha999** [comment]
@Wikinaut Thanks.
I think this should be by default that it doesn't auto-favorite a station that you press on to.

**Comment by Wikinaut** [comment]
Nope. You can disable it. As it is, it prevents newcomers from "losing" stations by default.

**Comment by Wikinaut** [comment]
You can easily fork the software if you wish other options.

**Comment by aha999** [comment]
Favorites is something you set, not that it's set automatically for everthing you press.
There's already a "history" menu that prevents newcomers from "losing" stations by default.

**Comment by Wikinaut** [comment]
@ah998 I also can agree with you. Please be informed that

* clicking onto the station *icon* always nevertheless sets/resets that station as a favorite (single click solution) - but does not start playing!
* the additional user option (I talked about above) enables/disables the set/reset-as-favorite when clicking onto the station name (single click solution for i) playing(!) and ii) set as favorite
* clicking the station always starts playing.

I use RadioDroid always since it was created and like the current behaviour very much - it is a single-click solution for my purposes. For users like you there is the option where you disable the auto-favoriting-when-playing. The setting survives program updates!

Please give the above describes varieties a chance and pehaps you want to try them, and perhaps you like my approach then. Main goal: at least clicks as possible. Single-click solution/s, if possible.

**Comment by werman** [comment]
Having the history, it's indeed a strange default behavior. On the other hand there is a solution for such type of options where there is no agreeable default: show user on the second/third launch a popup with several useful options.

**Comment by Wikinaut** [comment]
@werman There was also a technical reason for this as code is shared between the module. And so, the favorite view is the same as any other. One code basis, no extra schnickschnack. If someone wants to change this: go on but please leave me the single-click solutions as mentioned above. They work for years and nobody complained before.

**Comment by Wikinaut** [comment]
The title of the issue should be changed from

* Playing any radio automatically puts it to favorites

to

* Change user option default for "Auto-favorites"

**Comment by segler-alex** [comment]
i am for changing the default to "no", i think you can easily see your played streams in the history
