### ISSUE TITLE
[Contest] new logo: submit your logos for this app

### ISSUE THREAD

**Issue by zoff99** [segler-alex/RadioDroid#68]
please submit your logo suggestions here.
don't forget to make them CC BY-SA https://creativecommons.org/licenses/by-sa/2.0/

**Comment by zoff99** [comment]
#53

**Comment by conrad-heimbold** [comment]
@segler-alex and @zoff99 : what do you think about this idea: 
<image src="https://user-images.githubusercontent.com/17474312/27510199-074b9592-590c-11e7-94d3-bd912649b904.png"/>

? 
The arrow in the middle should look like a play button. 
I tried to fulfill your two requirements: 
- Listening (depicted by the play button)
- from all over the world

I know that you don't really recognize the arrow as play button. 
Therefore, we should maybe add something else to depict "music / sound": 
- a music note ( ♩ ♪ ♫ ♬ )
- or 'vibrations' / sound wave lines like this: ))) or ((( 

- for "listening", we could also use headphones. But then, we would have to leave out the arrow (otherwise we would have too much on the picture), also leaving out "all over the world"...

**Comment by Cormak** [comment]
@zoff99 I think we should adhere to the name of this app and create a modern icon where a little Android head has a radio dial on it. 

![radio](https://user-images.githubusercontent.com/11284950/33258175-7d25ca28-d30d-11e7-89d2-086c3a66bd03.png)

Like this but in the style of a green Android logo and with a Material Design look to it.

**Comment by segler-alex** [comment]
i like the current icon, sorry
