### ISSUE TITLE
Too easy to accidentally remove favorites by swiping

### ISSUE THREAD

**Issue by Vrihub** [segler-alex/RadioDroid#767]
It's still too easy to accidentally remove favorite stations by swiping them off the list, e.g. while picking up your phone, holding it, or even just tapping somewhere on the screen.

Please remove this annoying "feature" altogether: there is already a fully functional way to remove favorites (clicking the star icon below the station entry); the delete-by-swiping is totally useless and harmful.

**Comment by werman** [comment]
> clicking the star icon below the station entry

No one will find how to delete the station if this will be the only way. And there is the history list which also needs a way to remove items. 

> while picking up your phone, holding it

I think I see what's going wrong after trying to simulate what could going wrong in your case: if i do a short but quick swipe the - the station will be removed, I can see how this could accidentally happen

To sum up:
- The only real alternative to the swipe I see is adding a button to the expanded station state, however there are already too many of them there. 
- I think swipe to delete should be in the one direction after all
- The quick short swipe will also remove the station - this is prone to error

**Comment by Wikinaut** [comment]
Just as a comment: I  got used to the present method, even when I can understand @Vrihub s arguments.

**Comment by Vrihub** [comment]
> No one will find how to delete the station if this will be the only way.

I can't understand this. By the time you have _added_ a station to the favorites, you already know the way to delete it, i.e. by repeating the very same action.

Indeed we already have **two** ways for adding/removing: click on the star icon below the station entry, or on the station icon on the left (I forgot about that, since I disabled it in preferences).


> I think I see what's going wrong after trying to simulate what could going wrong in your case: if i do a short but quick swipe the - the station will be removed, I can see how this could accidentally happen

Exactly: it is awfully easy, especially with small devices and some very sensitive screens.


>  * The only real alternative to the swipe I see is adding a button to the expanded station state, however there are already too many of them there.

Oh no please. That is already too cluttered. And as I said before, we already have two ways for adding/removing. The swipe is really not needed.

**Comment by werman** [comment]
> I can't understand this. By the time you have added a station to the favorites, you already know the way to delete it, i.e. by repeating the very same action.

Yes, I agree (also you can add to favourites from full screen play but this doesn't matter), my thoughts just went some wrong direction.

In the end we must have a way to delete stations from history and swipe is the only good solution with current UI; so we have the same swipe to remove in favourites for consistency - it's not like we have enough of it. 

From my point of view the issue is not swipe-to-remove itself, but a certain edge cases: too big sensitivity, that it works in both directions, and undo button not being displayed long enough.

**Comment by werman** [comment]
After testing, I think removing the flinging (that's how this high velocity swipes are called) from swipes work good enough - there is no way to accidentally delete item with current thresholds, I may even need to reduce threshold of view being moved from 50% to maybe 35% I'll finish it tomorrow.

**Comment by summersab** [comment]
I know this is closed and done, but I would personally prefer to be able to disable swipes somewhere in the app's main settings. To remove a favorite, there could be a delete button to the right of the "Add to Home Screen" button when expanding out a station's details. That button could be there whether swipe is enabled or not, really, but I've never liked swipe actions for RecyclerView elements - I delete and archive stuff by accident all the time...

Presently, I get around this by enabling icon mode instead of list mode, so it's not a huge deal for me. I massively appreciate this app regardless!

**Comment by nekohayo** [comment]
There seems to be a follow-up ticket at #1191.
